source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'ReactiveCocoa', '~> 2.3.1'
pod 'Motis', '~>1.0.1'
pod 'SVProgressHUD'
pod 'SDWebImage', '~>3.6'
pod 'SSKeychain'
pod 'CRToast', '~> 0.0.7'
pod 'SIAlertView'
pod 'JJTabBarController', '~> 1.0.0'
pod 'HSDatePickerViewController', '~> 1.0'
pod 'ZYQAssetPickerController',  '~> 1.0.0'